name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Runs bats tests
    - uses: actions/bin/bats@master
    - args: test/*.bats
    - name: Runs shellcheck on scripts
    - uses: actions/bin/shellcheck@master
    - args: bin/*.sh
