name: CI

on: [push]

jobs:
  shellcheck:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run shellcheck on scripts
      uses: actions/bin/shellcheck@master
      with: 
        args: bin/*.sh
        
  bats:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run bats tests
      run: |
        sudo apt update
        sudo apt install -y bats
        bats test/*.bats
      
     # uses: actions/bin/bats@master
     # with: 
     #   args: test/*.bats
        
  test-run:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Test running script
      run: |
        bin/process_logs.sh log_files/*.tgz
        ls
        cat failed_login_summary.html
