name: CI

on: [push]

jobs:
  shellcheck:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run shellcheck on scripts
      uses: actions/bin/shellcheck@master
      with: 
        args: bin/*.sh
        
  bats:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run bats tests
      uses: actions/bin/bats@master
      with: 
        args: test/*.bats
