name: CI

on: [push]

jobs:
  shellcheck:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Runs bats tests
      uses: actions/bin/bats@master
      with: 
        args: test/*.bats
        
  bats:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Runs bats tests
      uses: actions/bin/bats@master
      with: 
        args: test/*.bats
